steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/performance-295311/github.com/sriashokreddy/nodejs:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/performance-295311/github.com/sriashokreddy/nodejs:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'nodejstestdeployment', '--platform=managed' '--region=europe-west1' '--image=gcr.io/performance-295311/github.com/sriashokreddy/nodejs:$SHORT_SHA']
